# Optional production overlay for Fedora 4 (Fcrepo4).

volumes:
  fcrepo:

services:
  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    volumes:
      - fcrepo:/data:cached
    env_file:
      - .env
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=fcrepo.hyku.test
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/jdbc-postgresql/repository.json" -Dfcrepo.postgresql.host=db -Dfcrepo.postgresql.username=${DB_USER} -Dfcrepo.postgresql.password=${DB_PASSWORD:-hyku} -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/fcrepo.binary.directory" -Djava.io.tmpdir="/data/tmp"
    expose:
      - 8080
    networks:
      internal:

  web:
    depends_on:
      fcrepo:
        condition: service_started

  worker:
    depends_on:
      fcrepo:
        condition: service_started

  initialize_app:
    depends_on:
      fcrepo:
        condition: service_started
