services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/samvera/hyku-minimal:${GITHUB_SHA:-latest}
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - .:/app/samvera/hyrax-webapp
      - bundle:/app/samvera/hyrax-webapp/vendor/bundle
    ports:
      - 3000:3000
volumes:
    bundle:
