label: Accessibility Hazards
description: >-
  Characteristics of a work that may pose a risk to some readers, such as
  flashing, motion, or sound.
terms:
  - id: Flashing
    term: Flashing
  - id: Motion
    term: Motion
  - id: Simulation
    term: Simulation
  - id: Sound
    term: Sound
