# To integrate your app with Google Analytics 4 (GA4) or Matomo, uncomment the
# lines below and provide your service credentials via environment variables.
# Note: You can only use one analytics service at a time.
#
analytics:
  ga4:
    analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
    property_id: <%= ENV['GOOGLE_ANALYTICS_PROPERTY_ID'] %>
    account_json: <%= ENV['GOOGLE_ACCOUNT_JSON'] %>
    account_json_path: <%= ENV['GOOGLE_ACCOUNT_JSON_PATH'] %>
  matomo:
    base_url: <%= ENV['MATOMO_BASE_URL'] %>
    site_id: <%= ENV['MATOMO_SITE_ID'] %>
    auth_token: <%= ENV['MATOMO_AUTH_TOKEN'] %>
