name: "Build Test Lint"
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_step:
        required: false
        description: "Pause the selected step to debug using tmate"
        type: choice
        default: ""
        options:
          - ""
          - build
          - test
          - lint

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: samvera/hyku
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    permissions: write-all
    uses: notch8/actions/.github/workflows/build.yaml@v1.0.9
    secrets: inherit
    with:
      components: '["web","worker","solr"]'

  lint:
    needs: build
    uses: notch8/actions/.github/workflows/lint.yaml@v1.0.9
    with:
      rubocop_cmd: "bundle exec rubocop --parallel --format progress"

  test:
    needs: build
    uses: notch8/actions/.github/workflows/test.yaml@v1.0.9
    with:
      confdir: "/app/samvera/hyrax-webapp/solr/conf"
      rspec_cmd: "gem install semaphore_test_boosters && bundle && rspec_booster --job $CI_NODE_INDEX/$CI_NODE_TOTAL"

  reports:
    if: always()
    needs: [test, lint]
    uses: notch8/actions/.github/workflows/report.yaml@v1.0.9