name: "Deploy"
run-name: Deploy (${{ github.ref_name }} -> ${{ inputs.environment }}) by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy to Environment"
        required: true
        default: "staging"
        type: choice
        options:
          # - demo - pausing for accessibility testing
          - iiif
          - staging
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

# We are using version 14 since this project has not been knap-sackerized yet
jobs:
  deploy:
    uses: notch8/actions/.github/workflows/deploy.yaml@v1.0.9
    secrets: inherit
